export const NEW_ORDER_REQUEST = 'NEW_ORDER_REQUEST'
export const NEW_ORDER_SUCCESS = 'NEW_ORDER_SUCCESS'
export const NEW_ORDER_FAIL = 'NEW_ORDER_FAIL'

export const CLEAR_ERROR = 'CLEAR_ERROR'

export const ALL_ORDERS_OF_A_USER_REQUEST = 'ALL_ORDERS_OF_A_USER_REQUEST'
export const ALL_ORDERS_OF_A_USER_SUCCESS = 'ALL_ORDERS_OF_A_USER_SUCCESS'
export const ALL_ORDERS_OF_A_USER_FAIL = 'ALL_ORDERS_OF_A_USER_FAIL'

export const GET_ALL_ORDERS_REQUEST = 'GET_ALL_ORDERS_REQUEST'
export const GET_ALL_ORDERS_SUCCESS = 'GET_ALL_ORDERS_SUCCESS'
export const GET_ALL_ORDERS_FAIL = 'GET_ALL_ORDERS_FAIL'