export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILURE = 'REGISTER_FAILURE'

export const CLEAR_ERROR = 'CLEAR_ERROR'

export const AUTO_LOGIN_REQUEST = 'AUTO_LOGIN_REQUEST'
export const AUTO_LOGIN_SUCCESS = 'AUTO_LOGIN_SUCCESS'
export const AUTO_LOGIN_FAIL = 'AUTO_LOGIN_FAIL'

export const GET_ALL_USERS_REQUEST = 'GET_ALL_USERS_REQUEST'
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS'
export const GET_ALL_USERS_FAIL = 'GET_ALL_USERS_FAIL'