export const CREATE_PRODUCT_REQUEST = 'CREATE_PRODUCT_REQUEST'
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS'
export const CREATE_PRODUCT_FAIL = 'CREATE_PRODUCT_FAIL'

export const GET_ALL_PRODUCTS_REQUEST = 'GET_ALL_PRODUCTS_REQUEST'
export const GET_ALL_PRODUCTS_SUCCESS = 'GET_ALL_PRODUCTS_SUCCESS'
export const GET_ALL_PRODUCTS_FAIL = 'GET_ALL_PRODUCTS_FAIL'

export const GET_PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST'
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS'
export const GET_PRODUCT_FAIL = 'GET_PRODUCT_FAIL'

export const GET_SEARCHED_PRODUCTS_REQUEST = 'GET_SEARCHED_PRODUCTS_REQUEST'
export const GET_SEARCHED_PRODUCTS_SUCCESS = 'GET_SEARCHED_PRODUCTS_SUCCESS'
export const GET_SEARCHED_PRODUCTS_FAIL = 'GET_SEARCHED_PRODUCTS_FAIL'


export const GET_ALL_PRODUCTS_ADMIN_REQUEST = 'GET_ALL_PRODUCTS_ADMIN_REQUEST'
export const GET_ALL_PRODUCTS_ADMIN_SUCCESS = 'GET_ALL_PRODUCTS_ADMIN_SUCCESS'
export const GET_ALL_PRODUCTS_ADMIN_FAIL = 'GET_ALL_PRODUCTS_ADMIN_FAIL'

export const ADD_REVIEW_REQUEST = 'ADD_REVIEW_REQUEST'
export const ADD_REVIEW_SUCCESS = 'ADD_REVIEW_SUCCESS'
export const ADD_REVIEW_FAIL = 'ADD_REVIEW_FAIL'

export const GET_PRODUCT_REVIEW_REQUEST = 'GET_PRODUCT_REVIEW_REQUEST'
export const GET_PRODUCT_REVIEW_SUCCESS = 'GET_PRODUCT_REVIEW_SUCCESS'
export const GET_PRODUCT_REVIEW_FAIL = 'GET_PRODUCT_REVIEW_FAIL'

export const CLEAR_ERROR = 'CLEAR_ERROR'
export const CLEAR_SUCCESS = 'CLEAR_SUCCESS'
